name: Review

on:
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/review.yml'


env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-mingw-w64-x86-64

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
          target: x86_64-pc-windows-gnu

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.8.1

      - name: clippy check
        uses: clechasseur/rs-clippy-check@v5.0.1
        with:
          args: --all-features
